### ISSUE TITLE
InvertAxis setting does not persist from Editor to Flight

### ISSUE THREAD

**Issue by erendrake** [MagicSmokeIndustries/InfernalRobotics#1]
_From @ZiwKerman on April 4, 2015 7:46_

Reported by kanddak

_Copied from original issue: erendrake/InfernalRobotics#84_

**Comment by erendrake** [comment]
_From @ZiwKerman on April 4, 2015 7:56_

it seems KSP does not like this

``` javascript
    [KSPField(isPersistant = true)]
        public bool invertAxis
        {
            get { return invertAxisStore;  }
            set
            {
                invertAxisStore = value;
                Events["InvertAxisToggle"].guiName = invertAxis ? "Axis Inverted. Revert?" : "Axis Normal. Invert?";
                TweakIsDirty = true;
            }
        }
```

**Comment by erendrake** [comment]
_From @ZiwKerman on April 4, 2015 8:21_

Yep, keybindings do not persist either.

**Comment by erendrake** [comment]
_From @ZiwKerman on April 4, 2015 11:25_

Reverting this to just

``` javascript
    [KSPField(isPersistant = true)]
        public bool invertAxis;
```

Solved the issue. Relocated some UI handling code to Mechanism. Will do the same for Keys

**Comment by ZiwKerman** [comment]
Fixed
