### ISSUE TITLE
IR Rotatron rotates opposite direction in space plane hangar vs simulation

### ISSUE THREAD

**Issue by Mogeley** [MagicSmokeIndustries/InfernalRobotics#109]
If I attach an IR Rotatron and tell it to rotate clock-wise in the space plane hangar, the Rotatron will rotate counter clock-wise in the simulation.

This makes part setup in the space plane hangar very difficult to not possible.

I am using the IR UI to control the Rotatron.

**Comment by ZiwKerman** [comment]
This issue was reported on the forums yesterday as well. This will be fixed in the next update, in the meanwhile you can test out this dll https://mega.nz/#!WQkmFQSR!zvrx3OZn_XD4mz2dPUa8vjbloTB92WkC7cA7o-xpRWI
Just overwrite your InfernalRobotics.dll with this one

**Comment by Mogeley** [comment]
Thanks, here's another issues I found.

In addition. There's several of issues with the IR Editor's display of current angle and setting movement limits in the Space Plane Hangar. This works properly in the simulation.

1) Setting movement limits in the space plane hangar changes the Rotatron's current angle display in the IR Editor. This angle change is carried over to the simulation causing problems in the simulation.
2) When parts are placed using mirroring mode; Setting movement limits on the mirrored part changes the current angle in the non mirrored part. The non-mirrored part looks like will display like it's movement is limited when it is not. The mirrored part's current angle is not changed, displays proper limits, and is limited the range.
3) Two Rotatrons that are placed using mirrored mode share minimum and maximum variables. However, to my knowledge none of the other values are shared.

**Comment by ZiwKerman** [comment]
As far as I know if you change range on the rotating part via rightclick menu KSP will apply the same settings to all of its symmetry counterparts. But when you change in the UI this does not happens usually. Problems come when you adjust them in the UI and then rightclick one of the parts - KSP may mess up some things. 

Anyway I'll do more tests in SPH when I have time.

**Comment by Mogeley** [comment]
Just dropped in the new DLL. the original issue is fixed. Thanks!

Just confirmed that 1,2, and 3 still exist only the current angle change is occurring in the correct row now!

Yes, I was using right-click menu to set limits. Now the behavior is a little different but using the right-click menu does copy the limit settings to the mirrored part.

I was not aware of the UI limits option. Just found it... That is much better. There's a couple issues with that as well:

a) When using an inverted axis the current angle is wrong, which prevents the range I want to be used. Ex: I want to limit to range 0 - 120 with inverted axis. After setting this the Current Angle is set to 120. The part can be rotated from 120 down to 0 which is the same range as 0-120 with non-inverted axis. I suppose I'm expecting that when I change the axis that it will rotate the opposite direction (which it does) and when setting a limit the current angle will stay the same.
b) When I turn on limits in the UI, I have to leave the options and re-enter to see the limit angles.

Thanks for you're work on this! Hope this is helpful.

**Comment by ZiwKerman** [comment]
a) is intended but b) needs to be fixed.
Will discuss a) internally again though

**Comment by ZiwKerman** [comment]
@Mogeley the initial issue should be fixed by #111 
So if you don't mind, please close this one, and open a new one for your subsequent question. Ir would help us keep track of pending issues better.
