### ISSUE TITLE
"Floating" extendatrons when using TweakScale

### ISSUE THREAD

**Issue by keyspace** [MagicSmokeIndustries/InfernalRobotics#113]
Scaled extendatrons are drawn misplaced (but work okay) if the parent pivotron is not in the default position. This happens on ship load.

It seems that:
- it doesn't matter if the parent pivotron is scaled or not;
- it doesn't matter if the parent is surface-attached or stuck to a radial attachment node.

**Screenshots**

Before reload:

![in orbit](https://cloud.githubusercontent.com/assets/18170434/15636484/ff9c2424-2608-11e6-8554-4b01c1417662.jpg)
![extended](https://cloud.githubusercontent.com/assets/18170434/15636485/ff9e6374-2608-11e6-867b-3a8150a12235.jpg)

After reload:

![reloaded game](https://cloud.githubusercontent.com/assets/18170434/15636483/ff9a9dfc-2608-11e6-9e5e-1881527ce65e.jpg)
![retracted](https://cloud.githubusercontent.com/assets/18170434/15636482/ff9a5c7a-2608-11e6-88b8-f6761bca2f1f.jpg)

**Test craft**
`IROutOfAlign.craft`: [gist](https://gist.github.com/keyspace/1f6f062c5ef7a7f2bb3e2e89cc52d968) or [raw](https://gist.githubusercontent.com/keyspace/1f6f062c5ef7a7f2bb3e2e89cc52d968/raw/3a431ed30771ece62de8c9f42277dedddebab6b2/IROutOfAlign.craft)

Top three "hands" are on a radial mount point, lower three are surface-attached. Some are scaled, some are not. Not all possible combinations are present.

**Reproducing**
1. Start a new sandbox game. For `KCT`, `RT`, `TACLS` and other mods which present dialogs, select "don't use" presets.
2. Load the provided craft in VAB.
3. Launch <strike>and achieve stable testing orbit (above 160 km, haven't tested on ground)</strike>.
4. Extend/pivot all `IR` parts to the next preset.
5. Force ship reload (either quicksave-quickload or go to space center, <strike>then tracking station,</strike> then back to vessel).
6. Observe: scaled extendatrons are "floating". Default-size are not.
7. Retract/pivot all `IR` parts back to default position.
8. Force ship reload.
9. Observe: all extendatrons are back to normal.

**Using**
- `Arch Linux` 64-bit
- `KSP` 1.1.2
- `CKAN` mods
  - `InfernalRobotics` 2.0.4
  - `TweakScale` 2.2.12
  - lots of others - hopefully irrelevant
- manual mods
  - `IR Model Rework - v02 Pre-Release Beta.zip`
  - `IRSequencer-1.0-RC1.zip`

Poke: @pellinor0 (`TweakScale`)

Related bugs: #79 

P.S. I actually wanted to file a different bug, with (scaled?) pivotrons drifting away from their surface attachment point, but can't reproduce that yet.

**Comment by ZiwKerman** [comment]
What is strange is that some of them did bug out and some of them stayed put.
I'll test it out today.

**Comment by ZiwKerman** [comment]
I can reproduce even on the Launchpad. Will be looking for a cause.

**Comment by ZiwKerman** [comment]
Oh, I see the problem, and it is not in the code. You attached the extendatrons incorrectly. Yellow arrows indicate a fixed mesh, and on your craft yellow arrow are on the outer edge of the craft (you have magnets attached to them). Once I reverted them, everything works as expected with no changes to the code needed.

**Comment by keyspace** [comment]
Ah! You are correct. The lights on the non-moving base mesh are to be on the outside when retracted. The arrows are obstructed by the non-scaled rotatron in some cases, but that's indeed not a code problem.

Should we leave the issue open, since the visual glitch is there when parts are attached incorrectly? Or should I move this to `TweakScale`'s bug tracker?..

**Comment by ZiwKerman** [comment]
It has nothing to do with Tweakscale I'm afraid, so there is no point in reporting it there.

I can try to detect incorrectly attached parts in VAB/SPH and issue a warning though. I'll create this as new feature request. 

#115
