### ISSUE TITLE
Rotatron's create mysterious internal forces with certain parts when NOT in motion

### ISSUE THREAD

**Issue by Mogeley** [MagicSmokeIndustries/InfernalRobotics#114]
Summary:
Rotatron's create mysterious internal forces with other parts in the same craft when the Rotatron is stationary. This is causing my crafts to twist and turn in very strangely eventually causing parts to fly off. So far the parts I know of are all Landing Struts.

Steps to Reproduce:
Build a super simple lander attached to something.
http://steamcommunity.com/sharedfiles/filedetails/?id=694327741
1. Start with some control unit 
2. Add Mk 1 Lander Can to bottom
3. Add 4x LT-2 landing struts to Lander Can using symmetry mode
4. Add Docking Port Jr to bottom of Lander Can
5. Add second Docking Port to docking port
6. Add Adapter to larger fuel tanks to docking port
7. Add Fuel tank to Adapter
8. Add Fuel tank to Fuel Tank
9. Add Launch Stability enhancer to fuel tank
10. Add IR Rotatron to either fuel tank
11. Launch and wait about 10 seconds.

Results: Lander Can will twist and push it's way off the docking port. The Landing struts may pop off as well.
http://steamcommunity.com/sharedfiles/filedetails/?id=694330878
http://steamcommunity.com/sharedfiles/filedetails/?id=694330785

Test 2: remove the Rotatron and Launch. 

Results: The vehicle sits still as expected.

Test 3: add the Rotatron back. Remove the Landing Struts and Launch

Results: The vehicle sits still as expected.

In this test only the LT-2 Landing Struts cause an issue. In a larger more complex lander all struts cause the issue and removing the Rotatrons makes the issue go away for all lander struts.

I've had this issue when using docking ports as well as strong connections using Stack Separators with struts. Docking ports make it easier to see the issue.

The issue seems like the Rotatrons are pushing the other parts away from it. However, distance doesn't seem to play a direct part. Some parts effect it more than others.

The effected parts are IR Rotatron and IR Rotatron Mk2. The Mark 2 part has the same behaviour only much less severe.

**Comment by ZiwKerman** [comment]
this issue was present in IR 2.0.3 but was fixed in IR 2.0.4
If you are still experiencing it in 2.0.4 - attach your log file (KSP.log)

The root of the issue is the infamous wheel auto-struts introduced by Squad in 1.1.2 which we have to deal with in IR in order to move stuff. Landing legs are considered wheels and therefore have auto-struts as well.

**Comment by Mogeley** [comment]
Awesome thanks! It's fixed in 2.0.4!
