### ISSUE TITLE
Inferno Robotics Parts glitching out when functioning "rotating, sliding, etc" (ksp 1.2)

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [MagicSmokeIndustries/InfernalRobotics#135]
Parts within the mod when put with the robotic parts tend not function properly without glitching or bugging off the parts attach to it than detaching off the vehicle if it bugs off too much. The robotic parts seem to be rendered unusable unless you want the whole ship to glitch and crash in a fury of a mess.

**Comment by RamsesIV** [comment]
Yeah I have same problem:/ it seems that the IR parts dont rotate right way and the parts attached to them looks like being kept from rotating. But in VAB everything works just fine...

**Comment by ZiwKerman** [comment]
Make sure you don't have Auto-Struts enabled and don't use KJR or know how to set it up so it does not affect IR parts.

**Comment by RamsesIV** [comment]
Ah thanks... KJR that was it, I just deleted it and it works like a charm :)
