### ISSUE TITLE
Gantry moving in wrong direction

### ISSUE THREAD

**Issue by pellinor0** [MagicSmokeIndustries/InfernalRobotics#18]
The gantry seems to move in the wrong direction in flight vs editor! This does not depend on scaling. So I move it to teh maximum (4) and launch. In flight, it starts at the same position, still reports pos=4, but refuses to move back on its rail. Instead it happily slides into the open air at the other side. 

So either the editor or the flight code moves gantries in the wrong direction. 

When I look at the code, the flight translation code has a gantryCorrection term. I do not find such a term in the editor code (doTranslation). Did this get lost in some recent refactoring?

**Comment by ZiwKerman** [comment]
It may have been lost in refactoring. Did you add it back, or you want me to add it to DoTranslation?

**Comment by pellinor0** [comment]
So far I just noticed the problem. It would be nice if you can do it, I'm currently pretty busy with TweakScale and other things.

**Comment by ZodiusInfuser** [comment]
I'm not able to reproduce this with the latest dlls from Slack. Gantry moves in the same direction in editor and in-flight and doesn't slide into the open air no matter what I try. I don't have your latest fixes to translational parts though so maybe they introduced a bug?

**Comment by pellinor0** [comment]
fixed by #24 (removed the gantry special treatment)
