### ISSUE TITLE
Change the way the EC is consumed by robotic parts.

### ISSUE THREAD

**Issue by erendrake** [MagicSmokeIndustries/InfernalRobotics#3]
_From @ZiwKerman on April 1, 2015 17:41_

This is not for the upcoming release, but we should really look into how IR consumes EC

_Copied from original issue: erendrake/InfernalRobotics#79_

**Comment by erendrake** [comment]
_From @ZiwKerman on April 2, 2015 21:34_

As an idea for future releases we may try to scale EC consumption with SQRT of servo speed over base/cfg speed, but then we would need to bring back EC consumption in UI somewhere.

**Comment by ZiwKerman** [comment]
The basic groundwork for this is in 2.0, now we need to add custom maxTorque to servomotors to take full advantage of it.
