### ISSUE TITLE
Check MoveCenter behaviour

### ISSUE THREAD

**Issue by erendrake** [MagicSmokeIndustries/InfernalRobotics#4]
_From @ZiwKerman on March 30, 2015 9:48_

Some users report that rotational parts return to As-Launched position and translational parts return to 0 position. 

_Copied from original issue: erendrake/InfernalRobotics#67_

**Comment by erendrake** [comment]
_From @ZiwKerman on April 1, 2015 17:34_

I was not able to reproduce.

**Comment by ZiwKerman** [comment]
This is closed by latest DefaultPosition changes
