### ISSUE TITLE
displaced translation parts move on rescale

### ISSUE THREAD

**Issue by erendrake** [MagicSmokeIndustries/InfernalRobotics#5]
_From @pellinor0 on March 21, 2015 21:57_

TweakScale considers the origin of the moving mesh as the center of the part, so this stays in place when changing scale. And the mesh that we consider fixed moves accordingly. 

I'd guess that this bug was already present in the old IR. 

_Copied from original issue: erendrake/InfernalRobotics#32_

**Comment by pellinor0** [comment]
Fixed by #19: we now move the part on rescale, so that the fixed mesh stays in the same place. The internal position is scaled in editor (because the model is scaled) but not in flight (because the saved position already refers to the scaled model).
