### ISSUE TITLE
IR log errors: WheelCollider requires an attached Rigidbody to function

### ISSUE THREAD

**Issue by Neouni** [MagicSmokeIndustries/InfernalRobotics#54]
WheelCollider requires an attached Rigidbody to function

**Comment by ZiwKerman** [comment]
Could you be more specific? Does this cause you any issues apart from this log message?

**Comment by Neouni** [comment]
No issues whatsoever
Guess it's something small in the model or the definitions

But the log is filled with it for IR parts

Actually, even some squad parts

**Comment by ZiwKerman** [comment]
Just ignore it. This happens during loading screen if I remember correctly when PartLoader tries to load all the parts. Essentially at this point it loads them one by one and wheel modules produce this error, but it is harmless.

**Comment by ZodiusInfuser** [comment]
That message can be ignored. To my knowledge Stock wheels also produce it, due to KSP setting up wheel colliders differently than what Unity expects.

Thanks for querying it though :)
