### ISSUE TITLE
Preset Prev and Next buttons in-editor should swap behaviour when Servo is inverted

### ISSUE THREAD

**Issue by ZodiusInfuser** [MagicSmokeIndustries/InfernalRobotics#58]
This is to be consistent with how the preset buttons behave in-flight, as it caused me a lot of confusion testing preset movements before launch.

**Comment by ZiwKerman** [comment]
That is odd, they should really be the same, unless there is a confusion related to inverted axis.

**Comment by ZiwKerman** [comment]
Fixed by #60
