### ISSUE TITLE
rotatrons turning where they are not supposed to

### ISSUE THREAD

**Issue by Ristellise** [MagicSmokeIndustries/InfernalRobotics#64]
![screenshot54](https://cloud.githubusercontent.com/assets/7894419/8228936/4b343fbe-15e5-11e5-9b2c-a4abcffad1d9.png)
In the editor ^^
![screenshot53](https://cloud.githubusercontent.com/assets/7894419/8228937/4b5948a4-15e5-11e5-8571-4bb03f92fcf5.png)
In the pictures above, i made 2 rotatrons turn the other way. however they turn the opposite side

**Comment by ZiwKerman** [comment]
Could you please post your .craft file? It seems like the inverted status has not persisted from editor to launchpad.

**Comment by Ristellise** [comment]
https://www.dropbox.com/s/9hx78rx4jashm0h/fix%20craft.craft?dl=0

**Comment by ZiwKerman** [comment]
Ok, it seems like a bug with legacy rotatron attached in mirror mode.

I'm not sure we can fix this in legacy parts quickly, but you can download Zodius Model Rework parts and use Rotatrons from there, they are tried and tested to behave properly.

**Comment by Ristellise** [comment]
Okay then

**Comment by ZiwKerman** [comment]
Legacy issue, cannot be solved right now.
