### ISSUE TITLE
Snapping issue from the forums

### ISSUE THREAD

**Issue by ZiwKerman** [MagicSmokeIndustries/InfernalRobotics#69]
I have found I'm having a new issue, never seen this one before but I haven't been working on my robotics for a while, been doing geometry. As such this may have come with the latest update.

It seems like my servos are snapping to limits when they get within a couple of degrees of a limit that has been set. A short video demo is included below.

This only occurs when two conditions are true:

1) The servo speed is set very low, and
2) The acceleration value is set very high.

The values at which the problem starts becoming visible are around servo speed about 0.2 or less and acceleration greater than 30.

To me it looks a heck of a lot like a rounding issue with acceleration.

https://youtu.be/55-jt7ic1qY

**Comment by pellinor0** [comment]
You probably fixed this one with https://github.com/MagicSmokeIndustries/InfernalRobotics/commit/bc0a6936208a53272d1a58b2071e109623a81bc9

**Comment by ZiwKerman** [comment]
Ah, yes.
