### ISSUE TITLE
IR Surface Sampler Integration

### ISSUE THREAD

**Issue by DMagic1** [MagicSmokeIndustries/InfernalRobotics#8]
How should the code for the [surface sampler](https://github.com/DMagic1/IR-Surface-Sampler) be handled?

It can be directly integrated into IR if you want, or just added here as a separate repo in the MagicSmokeIndustries group. Either way, it would make more sense to have it all together.

**Comment by ZodiusInfuser** [comment]
For me I think having a separate repo in this group would be better, since we'll be doing one for other mods we absorb too.
