### ISSUE TITLE
No parts (even in GameData) after installation from CKAN

### ISSUE THREAD

**Issue by davv1** [MagicSmokeIndustries/InfernalRobotics#97]
As title says. And there are screens:

![issue1b](https://cloud.githubusercontent.com/assets/13569795/14880697/91e834e0-0d30-11e6-8b21-d112bef18a44.png)

![issue1](https://cloud.githubusercontent.com/assets/13569795/14880600/ff735aa4-0d2f-11e6-8a19-7590f3a44f0b.png)

**Comment by ZiwKerman** [comment]
Please read the important notice here https://github.com/MagicSmokeIndustries/InfernalRobotics/releases/tag/2.0.0

An create issue on CKANs github, so the can include the Legacy Parts as a recommended download

**Comment by davv1** [comment]
They are included, @ZiwKerman but CKAN doesn't download them. They are marked as "Virtual" for 1.1.1230, probably not updated for versioncheck of CKAN. Any solution to make our lifes easier, please?

![issue1c](https://cloud.githubusercontent.com/assets/13569795/14880831/5ce7624c-0d31-11e6-9733-f751e5ccaf17.png)

**Comment by ZiwKerman** [comment]
I'll ask someone who knows CKAN better to help write a proper definition.

**Comment by davv1** [comment]
Thanks :)

**Comment by davv1** [comment]
What is the actual status of this issue, could you tell me? @ZiwKerman
